# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20180529_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
