# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_auto_20180530_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighbourhoodDetalis',
            new_name='NeighbourhoodDetails',
        ),
    ]
