# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20180530_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
