# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
