# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_auto_20180530_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
    ]
